### ISSUE TITLE
Way to NOT replace parent node?

### ISSUE THREAD

**Issue by laznic** [riot/hydrate#5]
I'm currently building an application with server side rendering and while the hydration and SSR is working just fine, I'm running in to a small problem when I'm using a Riot tag inside some other element, e.g. `<form>`. In short: hydrating is replacing my wrapping elements content with just the Riot tag content. Could this be prevented? More explanation below.

In my Handlebars template I'm rendering a Riot tag using a helper which renders the tag HTML correctly.
```
// template.hbs
<form method="post">
  <input type="text" name="name" placeholder="Placeholder" />
  {{{riot "components/common/search" riotOpts}}}
  <button type="submit">Submit</button>
</form>
```

```
// helper.js

const render = require('@riotjs/ssr').default
const Handlebars = require('handlebars')

module.exports = (pathFromTemplate, options) => {
  const splittedPath = pathFromTemplate.split('/')
  const tagName = splittedPath[splittedPath.length - 1]

  try {
    const tagPath = `../../tags/${pathFromTemplate}/${tagName}.riot`
    const tagtoRender = require(tagPath).default
    return render(tagtoRender.name, tagtoRender, {...options, isClient: false })

  } catch (err) {
    return new Handlebars.SafeString(`<span>No Riot tag "${tagName}" found in "${pathFromTemplate}".${err}</span>`)
  }
}
```
![image](https://user-images.githubusercontent.com/6230909/79239698-8b36fa00-7e79-11ea-8876-d0670818fd67.png)

**However** when I hydrate the component, it replaces the layout elements, leaving me with 
```<div class="content-wrapper" is="search"> {TAG_CONTENT_HERE} </div>```

![image](https://user-images.githubusercontent.com/6230909/79239875-bb7e9880-7e79-11ea-866f-e722adf53ccc.png)

```
// main.js - hydrating
const start = (components) => {
  const root = document.querySelector(".app .content-wrapper");

  components.forEach((tag) => {
    const component = tag.default;

    try {
      riot.register(component.name, component);

      if (document.querySelector(component.name))
        hydrate(component)(root, window.initialData);
    } catch (e) {
      console.log(e);
    }
  });
};
```

The hydration itself works perfectly fine, it sets the data and events correctly and the tag functions well. Currently the workaround is that I create a container tag with the `<form>` content and my Riot tag inside. For now it is ok, but I'd like to be able to only render single Riot tags here and there and leave the other static HTML parts to live in the layout files.

Not sure if this is a bug or a boolean flag that could be implemented in the library.

**Comment by GianlucaGuarini** [comment]
I think that you are misusing the hydrate API. Your Root tag should always bee your Riot component. I'll try to fix your code

```js

// simple helper to query dom nodes (I use bianco.query for it normally)
const $$ = (selector, parent) => Array.from(parent.querySelectorAll(component.name))

const start = (components) => {
  const root = document.querySelector(".app .content-wrapper")

  components.forEach((tag) => {
    const component = tag.default;
    // select the components by its name in the root tag
    const componentsNodes = $$(component.name, root)

    try {
      riot.register(component.name, component);
      // prepare the hydrate factory funciton
      const hydrateComponent = hydrate(component)
      
      // hydrate all the children component
      componentsNodes.forEach(node => hydrateComponent(root, window.initialData))
    } catch (e) {
      console.log(e);
    }
  });
};
```

**Comment by laznic** [comment]
Hey @GianlucaGuarini, thank you for getting back to this. I was supposed to put an update here today, but you got to it first.

Yes, you're correct. I was misusing the API and did change my code couple days agon to pretty much what you showed here. After this, everything works perfectly! 

Here is what my `start` function looks like now, however I'll add your `Array.from` etc. calls to improve it when I get the chance:
```
const start = (components) => {
  components.forEach((tag) => {
    const component = tag.default;

    try {
      riot.register(component.name, component);

      const root = document.querySelector(component.name);
      if (root) {
        hydrate(component)(root, window.initialData);
      }
      
    } catch (e) {
      console.log(e);
    }
  });
}
```

This issue can be closed now.
